### ISSUE TITLE
Installed package does not have any .js or tsx file

### ISSUE THREAD

**Issue by jiteshdhamaniya** [gabrielbs/react-placeholder-loading#20]
Hi mate, 
Once installed npm package it does not seems to have .js or tsx file in it..

**Comment by CAT6e** [comment]
Same in version 0.5.26

**Comment by gabrielbs** [comment]
thanks for the report! fixed on 0.5.27

https://github.com/gabrielbs/react-placeholder-loading/commit/233ff26a58eb823befcd163dafec778fb6a3ee00
